name: Bamboo CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Grant executable permission to gradlew
        run: chmod +x ./gradlew

      - name: Build and test
        run: |
          ./gradlew build test

      - name: Build Docker image
        run: |
          docker build -t bamboo:latest .

      - name: Return artifact
        run: |
          docker save my-app:latest | tar -cf artifact.tar -

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-artifact
          path: artifact.tar