name: Only tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Only run tests for ApiKeyService
        run: ./gradlew test -PtestGroups=ApiKeyService